version: '3.7'
services:
  app:
    build: .
    container_name: "guidy-server"
    ports:
    - "80:5001"
    volumes:
    - .:/usr/app
    environment:
    - NODE_ENV=dev-docker
    links:
    - mongodb
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongo-guidy"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    ports:
    - 27017:27017