version: '3.7'
services:
  app:
    build: .
    container_name: "guidy-server"
    ports:
    - "5001:5001"
    volumes:
    - .:/usr/app
    environment:
    - NODE_ENV=dev-docker
    links:
    - mongodb
    depends_on:
    - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb-guidy"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    ports:
    - 27019:27017
    command: mongod --smallfiles --logpath=/dev/null
